# Generated by Django 3.2.13 on 2022-07-26 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='What is your preffered name?')),
            ],
        ),
        migrations.CreateModel(
            name='UserFinancials_page3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideIncome', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you have a side income?')),
                ('MonthlySideIncome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Total Monthly side income')),
                ('Client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFinancials_page2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnABusiness', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Are you an owner of a business with cashflow?')),
                ('BusinessIncome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Average Monthly salary you recieve from your business?')),
                ('OwnShares', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you own shares in market?')),
                ('SharesWorth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Total shares worth?')),
                ('Client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFinancials_page1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('18', '<18'), ('1924', '19-24'), ('2530', '25-30'), ('3135', '31-35'), ('3640', '36-40'), ('4145', '41-45'), ('4650', '46-50'), ('5155', '51-55'), ('5660', '56-60'), ('60', '+60')], max_length=100, verbose_name='Age?')),
                ('lifeRole', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('Gran', 'GrandParent'), ('student', 'Student'), ('child', 'Son or Daughter'), ('Bachelor', 'Bachelor')], max_length=100, verbose_name='What is your life role of priority?')),
                ('NoOfDependants', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6+')], max_length=100, verbose_name='How many people are dependant to your income?')),
                ('Working', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Are you working for an income?')),
                ('Income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Income after tax')),
                ('Client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RentOrBond', models.CharField(choices=[('N', 'None'), ('B', 'Bond'), ('R', 'Rent')], max_length=100, verbose_name='Are you renting or paying a bond?')),
                ('RentingBondingPayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='How much do you pay in rent/bond?')),
                ('YearsLeftOfBond', models.CharField(blank=True, max_length=100, null=True, verbose_name='How many years do you have left in paying your bond?')),
                ('InterestOnBond', models.CharField(blank=True, max_length=100, null=True, verbose_name='Whats the interest on your bond?')),
                ('Rates', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montly rates and levies')),
                ('Client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Groceries', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly expenditure on Transport')),
                ('Transport', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly expenditure on Transport')),
                ('Electricity', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you buy electricity where you reside?')),
                ('ElectricityPayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monthly expenditure on electricity')),
                ('MembershipsAndSubscriptions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('Entertainment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly expenditure on entertainment')),
                ('Savings', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly payment to emergency funds')),
                ('PetOwner', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Are you a pet owner?')),
                ('PetsPayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monthly expenditure on your pets including insurance?')),
                ('InternetAndData', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly expenditure on data and airtime?')),
                ('CellPhoneContract', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you have a cellphone contract?')),
                ('CellphonePayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cellphone contract payment?')),
                ('Client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoOfContracts', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6+')], max_length=100, verbose_name='Number of contracts you pay monthly')),
                ('SchoolFees', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you pay school fees?')),
                ('SchoolFeesPayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='School Fees payment')),
                ('OwnACar', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you own a car?')),
                ('CarPayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Car installment')),
                ('HealthInsurance', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you have a cellphone contract?')),
                ('HealthInsurancePayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('LifeInsurance', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you have a life insurance policy?')),
                ('LifeInsurancePayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='life insurance policy contract payment?')),
                ('StudentLoan', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you have a life insurance policy?')),
                ('StudentLoanPayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('YearsLeftOfStudentLoan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Years left on student loan?')),
                ('InterestOnStudentLoan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Interest on student loan?')),
                ('OtherLoans', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you have a life insurance policy?')),
                ('OtherLoansPayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('YearsLeftOfOtherLoans', models.CharField(blank=True, max_length=100, null=True, verbose_name='Years left on other loan?')),
                ('InterestOnOtherLoans', models.CharField(blank=True, max_length=100, null=True, verbose_name='Interest on other loan?')),
                ('Retirement', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you have a life insurance policy?')),
                ('RetirementPayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('Client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddressOption', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Would you like to input your address information?')),
                ('StreetName', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                ('City', models.CharField(blank=True, max_length=100)),
                ('Province', models.CharField(blank=True, max_length=100, verbose_name='Province')),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('Client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
