# Generated by Django 3.2.13 on 2022-07-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thebudgetapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address_details',
            old_name='Client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='contracts',
            old_name='Client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='Client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userfinancials_page1',
            old_name='Client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userfinancials_page2',
            old_name='Client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userfinancials_page3',
            old_name='Client',
            new_name='user',
        ),
    ]
