# Generated by Django 3.2.13 on 2022-08-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebudgetapp', '0002_auto_20220726_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='CarPayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Car installment'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='HealthInsurancePayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='InterestOnOtherLoans',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Interest on other loan?'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='InterestOnStudentLoan',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Interest on student loan?'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='LifeInsurancePayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='life insurance policy contract payment?'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='OtherLoansPayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='RetirementPayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='SchoolFeesPayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='School Fees payment'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='StudentLoanPayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='YearsLeftOfOtherLoans',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Years left on other loan?'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='YearsLeftOfStudentLoan',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Years left on student loan?'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='CellphonePayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Cellphone contract payment?'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='ElectricityPayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Monthly expenditure on electricity'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='MembershipsAndSubscriptions',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='PetsPayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Monthly expenditure on your pets including insurance?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='InterestOnBond',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Whats the interest on your bond?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Rates',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Montly rates and levies'),
        ),
        migrations.AlterField(
            model_name='property',
            name='RentingBondingPayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='How much do you pay in rent/bond?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='YearsLeftOfBond',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='How many years do you have left in paying your bond?'),
        ),
        migrations.AlterField(
            model_name='userfinancials_page1',
            name='Income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Income after tax'),
        ),
        migrations.AlterField(
            model_name='userfinancials_page2',
            name='BusinessIncome',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Average Monthly salary you recieve from your business?'),
        ),
        migrations.AlterField(
            model_name='userfinancials_page2',
            name='SharesWorth',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Total shares worth?'),
        ),
        migrations.AlterField(
            model_name='userfinancials_page3',
            name='MonthlySideIncome',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Total Monthly side income'),
        ),
    ]
