# Generated by Django 3.2.13 on 2022-08-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebudgetapp', '0003_auto_20220804_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfinancials_page3',
            name='SideIncome',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, null=True, verbose_name='Do you have a side income?'),
        ),
    ]
