# Generated by Django 3.2.13 on 2022-08-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebudgetapp', '0004_alter_userfinancials_page3_sideincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Groceries',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly expenditure on groceries'),
        ),
        migrations.AlterField(
            model_name='userfinancials_page2',
            name='OwnShares',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Do you own shares in any company?'),
        ),
    ]
