# Generated by Django 3.2.13 on 2022-08-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebudgetapp', '0005_auto_20220816_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='CarPayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Car installment'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='InterestOnOtherLoans',
            field=models.CharField(blank=True, max_length=100, verbose_name='Interest on other loan?'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='InterestOnStudentLoan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Interest on student loan?'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='OtherLoansPayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='SchoolFeesPayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='School Fees payment'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='YearsLeftOfOtherLoans',
            field=models.CharField(blank=True, max_length=100, verbose_name='Years left on other loan?'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='YearsLeftOfStudentLoan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Years left on student loan?'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='CellphonePayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Cellphone contract payment?'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='ElectricityPayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Monthly expenditure on electricity'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='PetsPayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Monthly expenditure on your pets including insurance?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='RentingBondingPayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='How much do you pay in rent/bond?'),
        ),
        migrations.AlterField(
            model_name='userfinancials_page3',
            name='MonthlySideIncome',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Total Monthly side income'),
        ),
    ]
